services:
  - type: web
    name: pixelpositions
    runtime: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: JSEARCH_API_KEY
        sync: false  # Set this manually in Render dashboard
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 